# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_1/system_axi_dma_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_dma_1 || ORIG_REF_NAME==system_axi_dma_1} -quiet] -quiet

# IP: bd/system/ip/system_xbar_4/system_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_4 || ORIG_REF_NAME==system_xbar_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_2/system_axi_mem_intercon_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_2 || ORIG_REF_NAME==system_axi_mem_intercon_2} -quiet] -quiet

# IP: bd/system/ip/system_xbar_3/system_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_3 || ORIG_REF_NAME==system_xbar_3} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_intr_0_0/system_concat_intr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_concat_intr_0_0 || ORIG_REF_NAME==system_concat_intr_0_0} -quiet] -quiet

# IP: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_concat_intr_0_0/src/concat_intr_xlconcat_0_0/concat_intr_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==concat_intr_xlconcat_0_0 || ORIG_REF_NAME==concat_intr_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_0/system_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_example_0_0/system_example_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_example_0_0 || ORIG_REF_NAME==system_example_0_0} -quiet] -quiet

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_axi_dma_1/system_axi_dma_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_1 || ORIG_REF_NAME==system_axi_dma_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_axi_dma_1/system_axi_dma_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_1 || ORIG_REF_NAME==system_axi_dma_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_concat_intr_0_0/src/concat_intr_ooc.xdc

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_ooc.xdc

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: e:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/ip/system_example_0_0/constraints/example_ooc.xdc

# XDC: E:/estimation_accel/vivado/axi_stream_to_master_example/axi_stream_to_master_example.gen/sources_1/bd/system/system_ooc.xdc
