-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity byte_count is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC );
end;


architecture behav of byte_count is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "byte_count_byte_count,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010i-clg225-1L,HLS_INPUT_CLOCK=6.800000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.964000,HLS_SYN_LAT=649,HLS_SYN_TPT=391,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=3776,HLS_SYN_LUT=25543,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal input0_i_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal input0_t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal input1_i_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal input1_t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal input2_i_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal input2_t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal input3_i_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal input3_t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal appearances0_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances0_i_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances0_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances0_t_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances1_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances1_i_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances1_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances1_t_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances2_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances2_i_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances2_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances2_t_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances3_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances3_i_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances3_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal appearances3_t_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal combined_appearances_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal combined_appearances_i_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal combined_appearances_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal combined_appearances_t_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal split_U0_ap_start : STD_LOGIC;
    signal split_U0_ap_done : STD_LOGIC;
    signal split_U0_ap_continue : STD_LOGIC;
    signal split_U0_ap_idle : STD_LOGIC;
    signal split_U0_ap_ready : STD_LOGIC;
    signal split_U0_input_r_TREADY : STD_LOGIC;
    signal split_U0_output0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal split_U0_output0_ce0 : STD_LOGIC;
    signal split_U0_output0_we0 : STD_LOGIC;
    signal split_U0_output0_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal split_U0_output1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal split_U0_output1_ce0 : STD_LOGIC;
    signal split_U0_output1_we0 : STD_LOGIC;
    signal split_U0_output1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal split_U0_output2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal split_U0_output2_ce0 : STD_LOGIC;
    signal split_U0_output2_we0 : STD_LOGIC;
    signal split_U0_output2_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal split_U0_output3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal split_U0_output3_ce0 : STD_LOGIC;
    signal split_U0_output3_we0 : STD_LOGIC;
    signal split_U0_output3_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_channel_done_input3 : STD_LOGIC;
    signal split_U0_output3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_input3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_input3 : STD_LOGIC;
    signal ap_channel_done_input2 : STD_LOGIC;
    signal split_U0_output2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_input2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_input2 : STD_LOGIC;
    signal ap_channel_done_input1 : STD_LOGIC;
    signal split_U0_output1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_input1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_input1 : STD_LOGIC;
    signal ap_channel_done_input0 : STD_LOGIC;
    signal split_U0_output0_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_input0 : STD_LOGIC := '0';
    signal ap_sync_channel_write_input0 : STD_LOGIC;
    signal count_appearances_1_U0_ap_start : STD_LOGIC;
    signal count_appearances_1_U0_ap_done : STD_LOGIC;
    signal count_appearances_1_U0_ap_continue : STD_LOGIC;
    signal count_appearances_1_U0_ap_idle : STD_LOGIC;
    signal count_appearances_1_U0_ap_ready : STD_LOGIC;
    signal count_appearances_1_U0_input_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_1_U0_input_r_ce0 : STD_LOGIC;
    signal count_appearances_1_U0_appearances_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_1_U0_appearances_ce0 : STD_LOGIC;
    signal count_appearances_1_U0_appearances_we0 : STD_LOGIC;
    signal count_appearances_1_U0_appearances_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_appearances_1_U0_appearances_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_1_U0_appearances_ce1 : STD_LOGIC;
    signal count_appearances_1_U0_appearances_we1 : STD_LOGIC;
    signal count_appearances_1_U0_appearances_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_appearances_2_U0_ap_start : STD_LOGIC;
    signal count_appearances_2_U0_ap_done : STD_LOGIC;
    signal count_appearances_2_U0_ap_continue : STD_LOGIC;
    signal count_appearances_2_U0_ap_idle : STD_LOGIC;
    signal count_appearances_2_U0_ap_ready : STD_LOGIC;
    signal count_appearances_2_U0_input_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_2_U0_input_r_ce0 : STD_LOGIC;
    signal count_appearances_2_U0_appearances_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_2_U0_appearances_ce0 : STD_LOGIC;
    signal count_appearances_2_U0_appearances_we0 : STD_LOGIC;
    signal count_appearances_2_U0_appearances_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_appearances_2_U0_appearances_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_2_U0_appearances_ce1 : STD_LOGIC;
    signal count_appearances_2_U0_appearances_we1 : STD_LOGIC;
    signal count_appearances_2_U0_appearances_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_appearances_3_U0_ap_start : STD_LOGIC;
    signal count_appearances_3_U0_ap_done : STD_LOGIC;
    signal count_appearances_3_U0_ap_continue : STD_LOGIC;
    signal count_appearances_3_U0_ap_idle : STD_LOGIC;
    signal count_appearances_3_U0_ap_ready : STD_LOGIC;
    signal count_appearances_3_U0_input_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_3_U0_input_r_ce0 : STD_LOGIC;
    signal count_appearances_3_U0_appearances_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_3_U0_appearances_ce0 : STD_LOGIC;
    signal count_appearances_3_U0_appearances_we0 : STD_LOGIC;
    signal count_appearances_3_U0_appearances_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_appearances_3_U0_appearances_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_3_U0_appearances_ce1 : STD_LOGIC;
    signal count_appearances_3_U0_appearances_we1 : STD_LOGIC;
    signal count_appearances_3_U0_appearances_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_appearances_U0_ap_start : STD_LOGIC;
    signal count_appearances_U0_ap_done : STD_LOGIC;
    signal count_appearances_U0_ap_continue : STD_LOGIC;
    signal count_appearances_U0_ap_idle : STD_LOGIC;
    signal count_appearances_U0_ap_ready : STD_LOGIC;
    signal count_appearances_U0_input_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_U0_input_r_ce0 : STD_LOGIC;
    signal count_appearances_U0_appearances_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_U0_appearances_ce0 : STD_LOGIC;
    signal count_appearances_U0_appearances_we0 : STD_LOGIC;
    signal count_appearances_U0_appearances_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_appearances_U0_appearances_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_appearances_U0_appearances_ce1 : STD_LOGIC;
    signal count_appearances_U0_appearances_we1 : STD_LOGIC;
    signal count_appearances_U0_appearances_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal reduce_appearances_U0_ap_start : STD_LOGIC;
    signal reduce_appearances_U0_ap_done : STD_LOGIC;
    signal reduce_appearances_U0_ap_continue : STD_LOGIC;
    signal reduce_appearances_U0_ap_idle : STD_LOGIC;
    signal reduce_appearances_U0_ap_ready : STD_LOGIC;
    signal reduce_appearances_U0_appearances0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances0_ce0 : STD_LOGIC;
    signal reduce_appearances_U0_appearances0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances0_ce1 : STD_LOGIC;
    signal reduce_appearances_U0_appearances1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances1_ce0 : STD_LOGIC;
    signal reduce_appearances_U0_appearances1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances1_ce1 : STD_LOGIC;
    signal reduce_appearances_U0_appearances2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances2_ce0 : STD_LOGIC;
    signal reduce_appearances_U0_appearances2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances2_ce1 : STD_LOGIC;
    signal reduce_appearances_U0_appearances3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances3_ce0 : STD_LOGIC;
    signal reduce_appearances_U0_appearances3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_appearances3_ce1 : STD_LOGIC;
    signal reduce_appearances_U0_combined_apperances_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_combined_apperances_ce0 : STD_LOGIC;
    signal reduce_appearances_U0_combined_apperances_we0 : STD_LOGIC;
    signal reduce_appearances_U0_combined_apperances_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reduce_appearances_U0_combined_apperances_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal reduce_appearances_U0_combined_apperances_ce1 : STD_LOGIC;
    signal reduce_appearances_U0_combined_apperances_we1 : STD_LOGIC;
    signal reduce_appearances_U0_combined_apperances_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_threshold_U0_ap_start : STD_LOGIC;
    signal count_threshold_U0_ap_done : STD_LOGIC;
    signal count_threshold_U0_ap_continue : STD_LOGIC;
    signal count_threshold_U0_ap_idle : STD_LOGIC;
    signal count_threshold_U0_ap_ready : STD_LOGIC;
    signal count_threshold_U0_appearances_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_threshold_U0_appearances_ce0 : STD_LOGIC;
    signal count_threshold_U0_appearances_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal count_threshold_U0_appearances_ce1 : STD_LOGIC;
    signal count_threshold_U0_ap_return : STD_LOGIC_VECTOR (8 downto 0);
    signal output_channel_full_n : STD_LOGIC;
    signal Block_entry211_proc_U0_ap_start : STD_LOGIC;
    signal Block_entry211_proc_U0_ap_done : STD_LOGIC;
    signal Block_entry211_proc_U0_ap_continue : STD_LOGIC;
    signal Block_entry211_proc_U0_ap_idle : STD_LOGIC;
    signal Block_entry211_proc_U0_ap_ready : STD_LOGIC;
    signal Block_entry211_proc_U0_ap_return : STD_LOGIC_VECTOR (8 downto 0);
    signal output_load_cast_loc_channel_full_n : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_start : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_done : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_continue : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_idle : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_ready : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_return : STD_LOGIC_VECTOR (8 downto 0);
    signal input0_i_full_n : STD_LOGIC;
    signal input0_t_empty_n : STD_LOGIC;
    signal input1_i_full_n : STD_LOGIC;
    signal input1_t_empty_n : STD_LOGIC;
    signal input2_i_full_n : STD_LOGIC;
    signal input2_t_empty_n : STD_LOGIC;
    signal input3_i_full_n : STD_LOGIC;
    signal input3_t_empty_n : STD_LOGIC;
    signal appearances0_i_full_n : STD_LOGIC;
    signal appearances0_t_empty_n : STD_LOGIC;
    signal appearances1_i_full_n : STD_LOGIC;
    signal appearances1_t_empty_n : STD_LOGIC;
    signal appearances2_i_full_n : STD_LOGIC;
    signal appearances2_t_empty_n : STD_LOGIC;
    signal appearances3_i_full_n : STD_LOGIC;
    signal appearances3_t_empty_n : STD_LOGIC;
    signal combined_appearances_i_full_n : STD_LOGIC;
    signal combined_appearances_t_empty_n : STD_LOGIC;
    signal output_channel_dout : STD_LOGIC_VECTOR (8 downto 0);
    signal output_channel_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal output_channel_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal output_channel_empty_n : STD_LOGIC;
    signal output_load_cast_loc_channel_dout : STD_LOGIC_VECTOR (8 downto 0);
    signal output_load_cast_loc_channel_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal output_load_cast_loc_channel_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal output_load_cast_loc_channel_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component byte_count_split IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_TVALID : IN STD_LOGIC;
        input_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        input_r_TREADY : OUT STD_LOGIC;
        output0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output0_ce0 : OUT STD_LOGIC;
        output0_we0 : OUT STD_LOGIC;
        output0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output1_ce0 : OUT STD_LOGIC;
        output1_we0 : OUT STD_LOGIC;
        output1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output2_ce0 : OUT STD_LOGIC;
        output2_we0 : OUT STD_LOGIC;
        output2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output3_ce0 : OUT STD_LOGIC;
        output3_we0 : OUT STD_LOGIC;
        output3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component byte_count_count_appearances_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        appearances_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce0 : OUT STD_LOGIC;
        appearances_we0 : OUT STD_LOGIC;
        appearances_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce1 : OUT STD_LOGIC;
        appearances_we1 : OUT STD_LOGIC;
        appearances_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component byte_count_count_appearances_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        appearances_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce0 : OUT STD_LOGIC;
        appearances_we0 : OUT STD_LOGIC;
        appearances_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce1 : OUT STD_LOGIC;
        appearances_we1 : OUT STD_LOGIC;
        appearances_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component byte_count_count_appearances_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        appearances_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce0 : OUT STD_LOGIC;
        appearances_we0 : OUT STD_LOGIC;
        appearances_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce1 : OUT STD_LOGIC;
        appearances_we1 : OUT STD_LOGIC;
        appearances_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component byte_count_count_appearances IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        appearances_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce0 : OUT STD_LOGIC;
        appearances_we0 : OUT STD_LOGIC;
        appearances_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce1 : OUT STD_LOGIC;
        appearances_we1 : OUT STD_LOGIC;
        appearances_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        appearances_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component byte_count_reduce_appearances IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        appearances0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances0_ce0 : OUT STD_LOGIC;
        appearances0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances0_ce1 : OUT STD_LOGIC;
        appearances0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances1_ce0 : OUT STD_LOGIC;
        appearances1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances1_ce1 : OUT STD_LOGIC;
        appearances1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances2_ce0 : OUT STD_LOGIC;
        appearances2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances2_ce1 : OUT STD_LOGIC;
        appearances2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances3_ce0 : OUT STD_LOGIC;
        appearances3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances3_ce1 : OUT STD_LOGIC;
        appearances3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        combined_apperances_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        combined_apperances_ce0 : OUT STD_LOGIC;
        combined_apperances_we0 : OUT STD_LOGIC;
        combined_apperances_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        combined_apperances_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        combined_apperances_ce1 : OUT STD_LOGIC;
        combined_apperances_we1 : OUT STD_LOGIC;
        combined_apperances_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component byte_count_count_threshold IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        appearances_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce0 : OUT STD_LOGIC;
        appearances_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        appearances_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        appearances_ce1 : OUT STD_LOGIC;
        appearances_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component byte_count_Block_entry211_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (8 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component byte_count_Block_entry_proc_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (8 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component byte_count_input0_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component byte_count_appearances0_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        i_address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_ce1 : IN STD_LOGIC;
        i_we1 : IN STD_LOGIC;
        i_d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        i_q1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        t_address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_ce1 : IN STD_LOGIC;
        t_we1 : IN STD_LOGIC;
        t_d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        t_q1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component byte_count_fifo_w9_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (8 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component byte_count_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    input0_U : component byte_count_input0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => split_U0_output0_address0,
        i_ce0 => split_U0_output0_ce0,
        i_we0 => split_U0_output0_we0,
        i_d0 => split_U0_output0_d0,
        i_q0 => input0_i_q0,
        t_address0 => count_appearances_1_U0_input_r_address0,
        t_ce0 => count_appearances_1_U0_input_r_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv8_0,
        t_q0 => input0_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => input0_i_full_n,
        i_write => ap_channel_done_input0,
        t_empty_n => input0_t_empty_n,
        t_read => count_appearances_1_U0_ap_ready);

    input1_U : component byte_count_input0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => split_U0_output1_address0,
        i_ce0 => split_U0_output1_ce0,
        i_we0 => split_U0_output1_we0,
        i_d0 => split_U0_output1_d0,
        i_q0 => input1_i_q0,
        t_address0 => count_appearances_2_U0_input_r_address0,
        t_ce0 => count_appearances_2_U0_input_r_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv8_0,
        t_q0 => input1_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => input1_i_full_n,
        i_write => ap_channel_done_input1,
        t_empty_n => input1_t_empty_n,
        t_read => count_appearances_2_U0_ap_ready);

    input2_U : component byte_count_input0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => split_U0_output2_address0,
        i_ce0 => split_U0_output2_ce0,
        i_we0 => split_U0_output2_we0,
        i_d0 => split_U0_output2_d0,
        i_q0 => input2_i_q0,
        t_address0 => count_appearances_3_U0_input_r_address0,
        t_ce0 => count_appearances_3_U0_input_r_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv8_0,
        t_q0 => input2_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => input2_i_full_n,
        i_write => ap_channel_done_input2,
        t_empty_n => input2_t_empty_n,
        t_read => count_appearances_3_U0_ap_ready);

    input3_U : component byte_count_input0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => split_U0_output3_address0,
        i_ce0 => split_U0_output3_ce0,
        i_we0 => split_U0_output3_we0,
        i_d0 => split_U0_output3_d0,
        i_q0 => input3_i_q0,
        t_address0 => count_appearances_U0_input_r_address0,
        t_ce0 => count_appearances_U0_input_r_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv8_0,
        t_q0 => input3_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => input3_i_full_n,
        i_write => ap_channel_done_input3,
        t_empty_n => input3_t_empty_n,
        t_read => count_appearances_U0_ap_ready);

    appearances0_U : component byte_count_appearances0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => count_appearances_1_U0_appearances_address0,
        i_ce0 => count_appearances_1_U0_appearances_ce0,
        i_we0 => count_appearances_1_U0_appearances_we0,
        i_d0 => count_appearances_1_U0_appearances_d0,
        i_q0 => appearances0_i_q0,
        i_address1 => count_appearances_1_U0_appearances_address1,
        i_ce1 => count_appearances_1_U0_appearances_ce1,
        i_we1 => count_appearances_1_U0_appearances_we1,
        i_d1 => count_appearances_1_U0_appearances_d1,
        i_q1 => appearances0_i_q1,
        t_address0 => reduce_appearances_U0_appearances0_address0,
        t_ce0 => reduce_appearances_U0_appearances0_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => appearances0_t_q0,
        t_address1 => reduce_appearances_U0_appearances0_address1,
        t_ce1 => reduce_appearances_U0_appearances0_ce1,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv32_0,
        t_q1 => appearances0_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => appearances0_i_full_n,
        i_write => count_appearances_1_U0_ap_done,
        t_empty_n => appearances0_t_empty_n,
        t_read => reduce_appearances_U0_ap_ready);

    appearances1_U : component byte_count_appearances0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => count_appearances_2_U0_appearances_address0,
        i_ce0 => count_appearances_2_U0_appearances_ce0,
        i_we0 => count_appearances_2_U0_appearances_we0,
        i_d0 => count_appearances_2_U0_appearances_d0,
        i_q0 => appearances1_i_q0,
        i_address1 => count_appearances_2_U0_appearances_address1,
        i_ce1 => count_appearances_2_U0_appearances_ce1,
        i_we1 => count_appearances_2_U0_appearances_we1,
        i_d1 => count_appearances_2_U0_appearances_d1,
        i_q1 => appearances1_i_q1,
        t_address0 => reduce_appearances_U0_appearances1_address0,
        t_ce0 => reduce_appearances_U0_appearances1_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => appearances1_t_q0,
        t_address1 => reduce_appearances_U0_appearances1_address1,
        t_ce1 => reduce_appearances_U0_appearances1_ce1,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv32_0,
        t_q1 => appearances1_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => appearances1_i_full_n,
        i_write => count_appearances_2_U0_ap_done,
        t_empty_n => appearances1_t_empty_n,
        t_read => reduce_appearances_U0_ap_ready);

    appearances2_U : component byte_count_appearances0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => count_appearances_3_U0_appearances_address0,
        i_ce0 => count_appearances_3_U0_appearances_ce0,
        i_we0 => count_appearances_3_U0_appearances_we0,
        i_d0 => count_appearances_3_U0_appearances_d0,
        i_q0 => appearances2_i_q0,
        i_address1 => count_appearances_3_U0_appearances_address1,
        i_ce1 => count_appearances_3_U0_appearances_ce1,
        i_we1 => count_appearances_3_U0_appearances_we1,
        i_d1 => count_appearances_3_U0_appearances_d1,
        i_q1 => appearances2_i_q1,
        t_address0 => reduce_appearances_U0_appearances2_address0,
        t_ce0 => reduce_appearances_U0_appearances2_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => appearances2_t_q0,
        t_address1 => reduce_appearances_U0_appearances2_address1,
        t_ce1 => reduce_appearances_U0_appearances2_ce1,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv32_0,
        t_q1 => appearances2_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => appearances2_i_full_n,
        i_write => count_appearances_3_U0_ap_done,
        t_empty_n => appearances2_t_empty_n,
        t_read => reduce_appearances_U0_ap_ready);

    appearances3_U : component byte_count_appearances0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => count_appearances_U0_appearances_address0,
        i_ce0 => count_appearances_U0_appearances_ce0,
        i_we0 => count_appearances_U0_appearances_we0,
        i_d0 => count_appearances_U0_appearances_d0,
        i_q0 => appearances3_i_q0,
        i_address1 => count_appearances_U0_appearances_address1,
        i_ce1 => count_appearances_U0_appearances_ce1,
        i_we1 => count_appearances_U0_appearances_we1,
        i_d1 => count_appearances_U0_appearances_d1,
        i_q1 => appearances3_i_q1,
        t_address0 => reduce_appearances_U0_appearances3_address0,
        t_ce0 => reduce_appearances_U0_appearances3_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => appearances3_t_q0,
        t_address1 => reduce_appearances_U0_appearances3_address1,
        t_ce1 => reduce_appearances_U0_appearances3_ce1,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv32_0,
        t_q1 => appearances3_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => appearances3_i_full_n,
        i_write => count_appearances_U0_ap_done,
        t_empty_n => appearances3_t_empty_n,
        t_read => reduce_appearances_U0_ap_ready);

    combined_appearances_U : component byte_count_appearances0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => reduce_appearances_U0_combined_apperances_address0,
        i_ce0 => reduce_appearances_U0_combined_apperances_ce0,
        i_we0 => reduce_appearances_U0_combined_apperances_we0,
        i_d0 => reduce_appearances_U0_combined_apperances_d0,
        i_q0 => combined_appearances_i_q0,
        i_address1 => reduce_appearances_U0_combined_apperances_address1,
        i_ce1 => reduce_appearances_U0_combined_apperances_ce1,
        i_we1 => reduce_appearances_U0_combined_apperances_we1,
        i_d1 => reduce_appearances_U0_combined_apperances_d1,
        i_q1 => combined_appearances_i_q1,
        t_address0 => count_threshold_U0_appearances_address0,
        t_ce0 => count_threshold_U0_appearances_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => combined_appearances_t_q0,
        t_address1 => count_threshold_U0_appearances_address1,
        t_ce1 => count_threshold_U0_appearances_ce1,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv32_0,
        t_q1 => combined_appearances_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => combined_appearances_i_full_n,
        i_write => reduce_appearances_U0_ap_done,
        t_empty_n => combined_appearances_t_empty_n,
        t_read => count_threshold_U0_ap_ready);

    control_s_axi_U : component byte_count_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => ap_return);

    split_U0 : component byte_count_split
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => split_U0_ap_start,
        ap_done => split_U0_ap_done,
        ap_continue => split_U0_ap_continue,
        ap_idle => split_U0_ap_idle,
        ap_ready => split_U0_ap_ready,
        input_r_TVALID => input_r_TVALID,
        input_r_TDATA => input_r_TDATA,
        input_r_TREADY => split_U0_input_r_TREADY,
        output0_address0 => split_U0_output0_address0,
        output0_ce0 => split_U0_output0_ce0,
        output0_we0 => split_U0_output0_we0,
        output0_d0 => split_U0_output0_d0,
        output1_address0 => split_U0_output1_address0,
        output1_ce0 => split_U0_output1_ce0,
        output1_we0 => split_U0_output1_we0,
        output1_d0 => split_U0_output1_d0,
        output2_address0 => split_U0_output2_address0,
        output2_ce0 => split_U0_output2_ce0,
        output2_we0 => split_U0_output2_we0,
        output2_d0 => split_U0_output2_d0,
        output3_address0 => split_U0_output3_address0,
        output3_ce0 => split_U0_output3_ce0,
        output3_we0 => split_U0_output3_we0,
        output3_d0 => split_U0_output3_d0);

    count_appearances_1_U0 : component byte_count_count_appearances_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => count_appearances_1_U0_ap_start,
        ap_done => count_appearances_1_U0_ap_done,
        ap_continue => count_appearances_1_U0_ap_continue,
        ap_idle => count_appearances_1_U0_ap_idle,
        ap_ready => count_appearances_1_U0_ap_ready,
        input_r_address0 => count_appearances_1_U0_input_r_address0,
        input_r_ce0 => count_appearances_1_U0_input_r_ce0,
        input_r_q0 => input0_t_q0,
        appearances_address0 => count_appearances_1_U0_appearances_address0,
        appearances_ce0 => count_appearances_1_U0_appearances_ce0,
        appearances_we0 => count_appearances_1_U0_appearances_we0,
        appearances_d0 => count_appearances_1_U0_appearances_d0,
        appearances_address1 => count_appearances_1_U0_appearances_address1,
        appearances_ce1 => count_appearances_1_U0_appearances_ce1,
        appearances_we1 => count_appearances_1_U0_appearances_we1,
        appearances_d1 => count_appearances_1_U0_appearances_d1,
        appearances_q1 => appearances0_i_q1);

    count_appearances_2_U0 : component byte_count_count_appearances_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => count_appearances_2_U0_ap_start,
        ap_done => count_appearances_2_U0_ap_done,
        ap_continue => count_appearances_2_U0_ap_continue,
        ap_idle => count_appearances_2_U0_ap_idle,
        ap_ready => count_appearances_2_U0_ap_ready,
        input_r_address0 => count_appearances_2_U0_input_r_address0,
        input_r_ce0 => count_appearances_2_U0_input_r_ce0,
        input_r_q0 => input1_t_q0,
        appearances_address0 => count_appearances_2_U0_appearances_address0,
        appearances_ce0 => count_appearances_2_U0_appearances_ce0,
        appearances_we0 => count_appearances_2_U0_appearances_we0,
        appearances_d0 => count_appearances_2_U0_appearances_d0,
        appearances_address1 => count_appearances_2_U0_appearances_address1,
        appearances_ce1 => count_appearances_2_U0_appearances_ce1,
        appearances_we1 => count_appearances_2_U0_appearances_we1,
        appearances_d1 => count_appearances_2_U0_appearances_d1,
        appearances_q1 => appearances1_i_q1);

    count_appearances_3_U0 : component byte_count_count_appearances_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => count_appearances_3_U0_ap_start,
        ap_done => count_appearances_3_U0_ap_done,
        ap_continue => count_appearances_3_U0_ap_continue,
        ap_idle => count_appearances_3_U0_ap_idle,
        ap_ready => count_appearances_3_U0_ap_ready,
        input_r_address0 => count_appearances_3_U0_input_r_address0,
        input_r_ce0 => count_appearances_3_U0_input_r_ce0,
        input_r_q0 => input2_t_q0,
        appearances_address0 => count_appearances_3_U0_appearances_address0,
        appearances_ce0 => count_appearances_3_U0_appearances_ce0,
        appearances_we0 => count_appearances_3_U0_appearances_we0,
        appearances_d0 => count_appearances_3_U0_appearances_d0,
        appearances_address1 => count_appearances_3_U0_appearances_address1,
        appearances_ce1 => count_appearances_3_U0_appearances_ce1,
        appearances_we1 => count_appearances_3_U0_appearances_we1,
        appearances_d1 => count_appearances_3_U0_appearances_d1,
        appearances_q1 => appearances2_i_q1);

    count_appearances_U0 : component byte_count_count_appearances
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => count_appearances_U0_ap_start,
        ap_done => count_appearances_U0_ap_done,
        ap_continue => count_appearances_U0_ap_continue,
        ap_idle => count_appearances_U0_ap_idle,
        ap_ready => count_appearances_U0_ap_ready,
        input_r_address0 => count_appearances_U0_input_r_address0,
        input_r_ce0 => count_appearances_U0_input_r_ce0,
        input_r_q0 => input3_t_q0,
        appearances_address0 => count_appearances_U0_appearances_address0,
        appearances_ce0 => count_appearances_U0_appearances_ce0,
        appearances_we0 => count_appearances_U0_appearances_we0,
        appearances_d0 => count_appearances_U0_appearances_d0,
        appearances_address1 => count_appearances_U0_appearances_address1,
        appearances_ce1 => count_appearances_U0_appearances_ce1,
        appearances_we1 => count_appearances_U0_appearances_we1,
        appearances_d1 => count_appearances_U0_appearances_d1,
        appearances_q1 => appearances3_i_q1);

    reduce_appearances_U0 : component byte_count_reduce_appearances
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => reduce_appearances_U0_ap_start,
        ap_done => reduce_appearances_U0_ap_done,
        ap_continue => reduce_appearances_U0_ap_continue,
        ap_idle => reduce_appearances_U0_ap_idle,
        ap_ready => reduce_appearances_U0_ap_ready,
        appearances0_address0 => reduce_appearances_U0_appearances0_address0,
        appearances0_ce0 => reduce_appearances_U0_appearances0_ce0,
        appearances0_q0 => appearances0_t_q0,
        appearances0_address1 => reduce_appearances_U0_appearances0_address1,
        appearances0_ce1 => reduce_appearances_U0_appearances0_ce1,
        appearances0_q1 => appearances0_t_q1,
        appearances1_address0 => reduce_appearances_U0_appearances1_address0,
        appearances1_ce0 => reduce_appearances_U0_appearances1_ce0,
        appearances1_q0 => appearances1_t_q0,
        appearances1_address1 => reduce_appearances_U0_appearances1_address1,
        appearances1_ce1 => reduce_appearances_U0_appearances1_ce1,
        appearances1_q1 => appearances1_t_q1,
        appearances2_address0 => reduce_appearances_U0_appearances2_address0,
        appearances2_ce0 => reduce_appearances_U0_appearances2_ce0,
        appearances2_q0 => appearances2_t_q0,
        appearances2_address1 => reduce_appearances_U0_appearances2_address1,
        appearances2_ce1 => reduce_appearances_U0_appearances2_ce1,
        appearances2_q1 => appearances2_t_q1,
        appearances3_address0 => reduce_appearances_U0_appearances3_address0,
        appearances3_ce0 => reduce_appearances_U0_appearances3_ce0,
        appearances3_q0 => appearances3_t_q0,
        appearances3_address1 => reduce_appearances_U0_appearances3_address1,
        appearances3_ce1 => reduce_appearances_U0_appearances3_ce1,
        appearances3_q1 => appearances3_t_q1,
        combined_apperances_address0 => reduce_appearances_U0_combined_apperances_address0,
        combined_apperances_ce0 => reduce_appearances_U0_combined_apperances_ce0,
        combined_apperances_we0 => reduce_appearances_U0_combined_apperances_we0,
        combined_apperances_d0 => reduce_appearances_U0_combined_apperances_d0,
        combined_apperances_address1 => reduce_appearances_U0_combined_apperances_address1,
        combined_apperances_ce1 => reduce_appearances_U0_combined_apperances_ce1,
        combined_apperances_we1 => reduce_appearances_U0_combined_apperances_we1,
        combined_apperances_d1 => reduce_appearances_U0_combined_apperances_d1);

    count_threshold_U0 : component byte_count_count_threshold
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => count_threshold_U0_ap_start,
        ap_done => count_threshold_U0_ap_done,
        ap_continue => count_threshold_U0_ap_continue,
        ap_idle => count_threshold_U0_ap_idle,
        ap_ready => count_threshold_U0_ap_ready,
        appearances_address0 => count_threshold_U0_appearances_address0,
        appearances_ce0 => count_threshold_U0_appearances_ce0,
        appearances_q0 => combined_appearances_t_q0,
        appearances_address1 => count_threshold_U0_appearances_address1,
        appearances_ce1 => count_threshold_U0_appearances_ce1,
        appearances_q1 => combined_appearances_t_q1,
        ap_return => count_threshold_U0_ap_return);

    Block_entry211_proc_U0 : component byte_count_Block_entry211_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry211_proc_U0_ap_start,
        ap_done => Block_entry211_proc_U0_ap_done,
        ap_continue => Block_entry211_proc_U0_ap_continue,
        ap_idle => Block_entry211_proc_U0_ap_idle,
        ap_ready => Block_entry211_proc_U0_ap_ready,
        p_read => output_channel_dout,
        ap_return => Block_entry211_proc_U0_ap_return);

    Block_entry_proc_proc_U0 : component byte_count_Block_entry_proc_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry_proc_proc_U0_ap_start,
        ap_done => Block_entry_proc_proc_U0_ap_done,
        ap_continue => Block_entry_proc_proc_U0_ap_continue,
        ap_idle => Block_entry_proc_proc_U0_ap_idle,
        ap_ready => Block_entry_proc_proc_U0_ap_ready,
        p_read => output_load_cast_loc_channel_dout,
        ap_return => Block_entry_proc_proc_U0_ap_return);

    output_channel_U : component byte_count_fifo_w9_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => count_threshold_U0_ap_return,
        if_full_n => output_channel_full_n,
        if_write => count_threshold_U0_ap_done,
        if_dout => output_channel_dout,
        if_num_data_valid => output_channel_num_data_valid,
        if_fifo_cap => output_channel_fifo_cap,
        if_empty_n => output_channel_empty_n,
        if_read => Block_entry211_proc_U0_ap_ready);

    output_load_cast_loc_channel_U : component byte_count_fifo_w9_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_entry211_proc_U0_ap_return,
        if_full_n => output_load_cast_loc_channel_full_n,
        if_write => Block_entry211_proc_U0_ap_done,
        if_dout => output_load_cast_loc_channel_dout,
        if_num_data_valid => output_load_cast_loc_channel_num_data_valid,
        if_fifo_cap => output_load_cast_loc_channel_fifo_cap,
        if_empty_n => output_load_cast_loc_channel_empty_n,
        if_read => Block_entry_proc_proc_U0_ap_ready);





    ap_sync_reg_channel_write_input0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_input0 <= ap_const_logic_0;
            else
                if (((split_U0_ap_done and split_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_input0 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_input0 <= ap_sync_channel_write_input0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_input1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_input1 <= ap_const_logic_0;
            else
                if (((split_U0_ap_done and split_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_input1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_input1 <= ap_sync_channel_write_input1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_input2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_input2 <= ap_const_logic_0;
            else
                if (((split_U0_ap_done and split_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_input2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_input2 <= ap_sync_channel_write_input2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_input3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_input3 <= ap_const_logic_0;
            else
                if (((split_U0_ap_done and split_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_input3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_input3 <= ap_sync_channel_write_input3;
                end if; 
            end if;
        end if;
    end process;

    Block_entry211_proc_U0_ap_continue <= output_load_cast_loc_channel_full_n;
    Block_entry211_proc_U0_ap_start <= output_channel_empty_n;
    Block_entry_proc_proc_U0_ap_continue <= ap_const_logic_1;
    Block_entry_proc_proc_U0_ap_start <= output_load_cast_loc_channel_empty_n;
    ap_channel_done_input0 <= (split_U0_ap_done and (ap_sync_reg_channel_write_input0 xor ap_const_logic_1));
    ap_channel_done_input1 <= (split_U0_ap_done and (ap_sync_reg_channel_write_input1 xor ap_const_logic_1));
    ap_channel_done_input2 <= (split_U0_ap_done and (ap_sync_reg_channel_write_input2 xor ap_const_logic_1));
    ap_channel_done_input3 <= (split_U0_ap_done and (ap_sync_reg_channel_write_input3 xor ap_const_logic_1));
    ap_done <= Block_entry_proc_proc_U0_ap_done;
    ap_idle <= (split_U0_ap_idle and reduce_appearances_U0_ap_idle and (output_load_cast_loc_channel_empty_n xor ap_const_logic_1) and (output_channel_empty_n xor ap_const_logic_1) and (combined_appearances_t_empty_n xor ap_const_logic_1) and (appearances3_t_empty_n xor ap_const_logic_1) and (appearances2_t_empty_n xor ap_const_logic_1) and (appearances1_t_empty_n xor ap_const_logic_1) and (appearances0_t_empty_n xor ap_const_logic_1) and (input3_t_empty_n xor ap_const_logic_1) and (input2_t_empty_n xor ap_const_logic_1) and (input1_t_empty_n xor ap_const_logic_1) and (input0_t_empty_n xor ap_const_logic_1) and count_threshold_U0_ap_idle and count_appearances_U0_ap_idle and count_appearances_3_U0_ap_idle and count_appearances_2_U0_ap_idle and count_appearances_1_U0_ap_idle and Block_entry_proc_proc_U0_ap_idle and Block_entry211_proc_U0_ap_idle);
    ap_ready <= split_U0_ap_ready;
    ap_return <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Block_entry_proc_proc_U0_ap_return),32));

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_channel_write_input0 <= ((split_U0_output0_full_n and ap_channel_done_input0) or ap_sync_reg_channel_write_input0);
    ap_sync_channel_write_input1 <= ((split_U0_output1_full_n and ap_channel_done_input1) or ap_sync_reg_channel_write_input1);
    ap_sync_channel_write_input2 <= ((split_U0_output2_full_n and ap_channel_done_input2) or ap_sync_reg_channel_write_input2);
    ap_sync_channel_write_input3 <= ((split_U0_output3_full_n and ap_channel_done_input3) or ap_sync_reg_channel_write_input3);
    count_appearances_1_U0_ap_continue <= appearances0_i_full_n;
    count_appearances_1_U0_ap_start <= input0_t_empty_n;
    count_appearances_2_U0_ap_continue <= appearances1_i_full_n;
    count_appearances_2_U0_ap_start <= input1_t_empty_n;
    count_appearances_3_U0_ap_continue <= appearances2_i_full_n;
    count_appearances_3_U0_ap_start <= input2_t_empty_n;
    count_appearances_U0_ap_continue <= appearances3_i_full_n;
    count_appearances_U0_ap_start <= input3_t_empty_n;
    count_threshold_U0_ap_continue <= output_channel_full_n;
    count_threshold_U0_ap_start <= combined_appearances_t_empty_n;
    input_r_TREADY <= split_U0_input_r_TREADY;
    reduce_appearances_U0_ap_continue <= combined_appearances_i_full_n;
    reduce_appearances_U0_ap_start <= (appearances3_t_empty_n and appearances2_t_empty_n and appearances1_t_empty_n and appearances0_t_empty_n);
    split_U0_ap_continue <= (ap_sync_channel_write_input3 and ap_sync_channel_write_input2 and ap_sync_channel_write_input1 and ap_sync_channel_write_input0);
    split_U0_ap_start <= ap_start;
    split_U0_output0_full_n <= input0_i_full_n;
    split_U0_output1_full_n <= input1_i_full_n;
    split_U0_output2_full_n <= input2_i_full_n;
    split_U0_output3_full_n <= input3_i_full_n;
end behav;
