@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Sun Sep 18 15:37:10 -0500 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: compile.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path="C:/Xilinx/Vivado/2022.1/data/xsim"
set xv_cpt_lib_path="C:/Xilinx/Vivado/2022.1/data/simmodels/xsim/2022.1/win64/6.2.0/systemc/protected"
set xv_ext_lib_path="C:/Xilinx/Vivado/2022.1/data/simmodels/xsim/2022.1/win64/6.2.0/ext"
set xv_boost_lib_path="C:/Xilinx/Vivado/2022.1/tps/boost_1_72_0"

REM compile systemC design sources
echo "xsc -c --gcc_compile_options "-DBOOST_SYSTEM_NO_DEPRECATED" --gcc_compile_options "-I../../../../zc702_estimation_platform.ip_user_files/bd/system/ip/system_processing_system7_0_0/sim_tlm -I../../../../zc702_estimation_platform.gen/sources_1/bd/system/ip/system_processing_system7_0_0/sim_tlm -I../../../../zc702_estimation_platform.ip_user_files/bd/system/ip/system_processing_system7_0_0/sim -I%xv_boost_lib_path% -I%xv_cxl_lib_path%/ip/remote_port_c_v4/include -I%xv_cxl_lib_path%/ip/common_cpp_v1_0/include -I%xv_cxl_lib_path%/ip/xtlm/include" -work xil_defaultlib -f system_wrapper_xsc.prj"
call xsc  -c --gcc_compile_options "-DBOOST_SYSTEM_NO_DEPRECATED" --gcc_compile_options "-I../../../../zc702_estimation_platform.ip_user_files/bd/system/ip/system_processing_system7_0_0/sim_tlm -I../../../../zc702_estimation_platform.gen/sources_1/bd/system/ip/system_processing_system7_0_0/sim_tlm -I../../../../zc702_estimation_platform.ip_user_files/bd/system/ip/system_processing_system7_0_0/sim -I%xv_boost_lib_path% -I%xv_cxl_lib_path%/ip/remote_port_c_v4/include -I%xv_cxl_lib_path%/ip/common_cpp_v1_0/include -I%xv_cxl_lib_path%/ip/xtlm/include" -work xil_defaultlib -f system_wrapper_xsc.prj 2> xsc_err.log
call type xsc.log >> compile.log
call type xsc_err.log >> compile.log
call type xsc_err.log
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -L axi_vip_v1_1_12 -L processing_system7_vip_v1_0_14 -L xilinx_vip -prj system_wrapper_vlog.prj"
call xvlog  --incr --relax -L uvm -L axi_vip_v1_1_12 -L processing_system7_vip_v1_0_14 -L xilinx_vip -prj system_wrapper_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
REM compile VHDL design sources
echo "xvhdl --incr --relax -prj system_wrapper_vhdl.prj"
call xvhdl  --incr --relax -prj system_wrapper_vhdl.prj -log xvhdl.log
call type xvhdl.log >> compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
